const Users = [
  {
    id: 1,
    name: "Faiz Ahmad",
    title: "Full-Stack Developer at Codynect",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    mutual: 5,
    requested: false,
    invite: false,
    isConnected: true,
  },
  {
    id: 2,
    name: "Aisha Kapoor",
    title: "UI/UX Designer at Zync",
    avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    mutual: 3,
    requested: true,
    invite: false,
    isConnected: false,
  },
  {
    id: 3,
    name: "Rohan Verma",
    title: "AI Intern • CodX Labs",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    mutual: 2,
    requested: true,
    invite: true,
    isConnected: false,
  },
  {
    id: 4,
    name: "Neha Sharma",
    title: "Backend Developer at Initech",
    avatar: "https://randomuser.me/api/portraits/women/51.jpg",
    mutual: 6,
    requested: true,
    invite: false,
    isConnected: false,
  },
  {
    id: 5,
    name: "Aryan Khanna",
    title: "Data Scientist at Quantigo",
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    mutual: 1,
    requested: true,
    invite: true,
    isConnected: false,
  },
  {
    id: 6,
    name: "Tanya Bhatt",
    title: "Mobile App Developer at Appify",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    mutual: 4,
    requested: false,
    invite: false,
    isConnected: true,
  },
  {
    id: 7,
    name: "Kabir Mehta",
    title: "DevOps Engineer at InfraX",
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    mutual: 2,
    requested: true,
    invite: false,
    isConnected: false,
  },
  {
    id: 8,
    name: "Sneha Rathi",
    title: "Frontend Developer at BrightWeb",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    mutual: 3,
    requested: false,
    invite: true,
    isConnected: false,
  },
  {
    id: 9,
    name: "Dev Malhotra",
    title: "ML Engineer at DeepTech",
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    mutual: 5,
    requested: false,
    invite: false,
    isConnected: false,
  },
  {
    id: 10,
    name: "Nikita Jain",
    title: "Product Manager at ScaleUp",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    mutual: 4,
    requested: true,
    invite: false,
    isConnected: true,
  },
];

export default Users;
